### PR TITLE
fix: memory leaks

### LINKED ISSUE #10: memory leaks
The `rpcClient` code in `exchange.js` has some memory leaks.
I found 3 places with problems:

1 - the `publish` function is storing a correlationId in a [`pendingReplies`](https://github.com/pagerinc/jackrabbit/blob/master/lib/exchange.js#L182) object, but it never clears that correlationId when receiving the reply.
So this object is gonna keep growing on each message sent. This is particularly dangerous on Pager APIs where the `exchange` object is instantiated only once per server.

2 - Inside the `rpcClient` function [three functions](https://github.com/pagerinc/jackrabbit/blob/master/lib/exchange.js#L84) are created and passed to the `publish` method (`timeout`, `onNotFound` and `onReply`). None of these functions clears the corresponding reply on the `pendingReplies` object, so the problem with (1) repeats.

3 - The `publish` function is [adding](https://github.com/pagerinc/jackrabbit/blob/master/lib/exchange.js#L186) a listener to the `return` event on the `channel`, but it never clears that listener, so this causes another memory leak and a node warning: 
`Warning: Possible EventEmitter memory leak detected. 11 return listeners added. Use emitter.setMaxListeners() to increase limit`

### PR DESCRIPTION
**Pull request by marianoquevedo**
closes #10 by:

Refactoring the `rpcClient` functionality, separating the `publish` function in two to have more control over the way the responses are managed.

**fixes for problems 1 & 2:**
delete from the `pendingReplies` object when a reply is received, timeouts or the destination queue is not found.

**fix for problem 3:**
remove the listener on the channel when a reply is received, timeouts or the destination queue is not found:  `channel.removeListener('return', onNotFound);`

### CODE REVIEW

File: lib/exchange.js [hunk 1]
```diff
@@ -246,4 +294,4 @@ function exchange(name, type, options) {
   function isNameless(name) {
     return name === '';
   }
-}
+}
```
Comment (kuryaki) [inline lib/exchange.js]: LGTM just add new line at end of file
